# DEFAULT
# Spring Boot configuration
spring:
  profiles:
    active: dev
  mvc:
    servlet:
      path: /api/search/v1
    log-request-details: false
    log-resolved-exception: false

server:
  port: 8080

logging:
  level:
    root: warn
    ex.org.project.search:
      SearchApplication: info
    org.springframework.web.servlet:
      DispatcherServlet: trace
      mvc.method.annotation:
        HttpEntityMethodProcessor: trace

management:
  endpoint:
    health:
      show-details: never
      enabled: true
  health:
    elasticsearch:
      enabled: false
  endpoints:
    web:
      exposure:
        include: health
    enabled-by-default: false

opensearch:
  hostname: ${opensearch.hostname}
  port: ${opensearch.port}
  scheme: ${opensearch.scheme}
  username: ${opensearch.username}
  password: ${opensearch.password}
  index:
    studies: study_search
    autocomplete: study_autocomplete_v001

query:
  min-score-ratio: 0.2
  exact-fields:
    title: 1.5
    description: 0.75
    subject: 2.0
    data_general_types: 2.0
    dcc: 0.5
    types: 2.0
    source: 2.0
    topics: 2.0
    phs: 1.0
    study_population_focus: 2.0
    study_variables: 1.0
    institutes_supporting_study: 0.5
    study_DOI: 0.2
    pi_name: 0.5
    multi_center_sites: 1.0
    grant_number: 1.0
  fuzzy-fields:
    title: 1.2
    description: 0.6
    subject: 1.6
    data_general_types: 1.6
    types: 1.6
    source: 1.6
    topics: 1.6
    study_population_focus: 1.6
    study_variables: 1.0
    pi_name: 0.25
    multi_center_sites: 0.8
  partial-fields:
    title: .75
    description: 0.45
    subject: 1.0
    data_general_types: 1.0
    types: 1.0
    source: 1.0
    topics: 1.0
    study_population_focus: 1.0
    study_variables: 1.0
    multi_center_sites: 0.25
  aggregation-fields:
    - "dcc"
    - "source_array"
    - "title"
    - "subject_array"
    - "types_array"
    - "topics_array"
    - "institutes_supporting_study_array"
    - "data_general_types_array"
    - "has_data_files"
    - "estimated_participant_range"
    - "study_population_focus_array"
    - "study_variables_array"
  sorting-fields:
    phs: phs.keyword
    title: title.keyword
    dcc: dcc.keyword
    relevance: _score

apis:
  host: ${HostURL}
  entity-service:
    getProps: /api/entity/v1/search/getProps

database:
  db-user: ${dbuser}
  db-password: ${password}
  host: ${host}
  port: ${port}
  db-name: ${dbname}

---
# LOCAL

spring:
  config:
    activate:
      on-profile: local

management:
  endpoint:
    health:
      show-details: always

opensearch:
  hostname: search-os-dev-o3trnur44rfx5cdpepqrjqbsri.us-east-2.es.amazonaws.com
  port: 443
  scheme: https
  username: ${SEARCH_USERNAME}
  password: ${SEARCH_PASSWORD}
  index:
    studies: study_search
    autocomplete: study_autocomplete_v001

logging:
  pattern:
    console: "[%boldMagenta(SEARCH)] [%boldGreen(LOCAL)] %d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) --- [%cyan(%15.15t)] %-40.40logger{1.} %boldYellow(::) %m%n%wEx"

---
# DEV

spring:
  config:
    import: aws-secretsmanager:application_dev
    activate:
      on-profile: dev

management:
  endpoint:
    health:
      show-details: always

logging:
  pattern:
    console: "[%boldMagenta(SEARCH)] [%boldGreen(DEV)] %d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) --- [%cyan(%15.15t)] %-40.40logger{1.} %boldYellow(::) %m%n%wEx"

---
# TEST

spring:
  config:
    import: aws-secretsmanager:application_test
    activate:
      on-profile: test

logging:
  pattern:
    console: "[%boldMagenta(SEARCH)] [%boldGreen(TEST)] %d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) --- [%cyan(%15.15t)] %-40.40logger{1.} %boldYellow(::) %m%n%wEx"

---
# PROD

spring:
  config:
    import: aws-secretsmanager:application_prod
    activate:
      on-profile: prod

logging:
  pattern:
    console: "[%boldMagenta(SEARCH)] [%boldGreen(PROD)] %d{yyyy-MM-dd HH:mm:ss.SSS} %highlight([%5p]) --- [%cyan(%15.15t)] %-40.40logger{1.} %boldYellow(::) %m%n%wEx"
